const API = (() => {
  const configured = window.DOGTALK_API_URL?.trim();
  if (configured) return configured.replace(/\/$/, '');
  const host = window.location.hostname;
  return ['localhost', '127.0.0.1', '::1', ''].includes(host) ? 'http://127.0.0.1:8000' : '';
})();

// Real recorded dog bark. This replaces the previous Web Audio synthetic tone.
const REAL_DOG_BARK_URL = 'https://orangefreesounds.com/wp-content/uploads/2026/04/Dog-barking-sound-effect-loud-natural-bark.mp3';
const $ = id => document.getElementById(id);
let dogRecorder = null, dogChunks = [], humanRecorder = null, recognition = null, transcript = '';

function setRecordingUI(waveId, statusId, active, message) {
  $(waveId).classList.toggle('active', active);
  $(statusId).textContent = message;
}
function apiUrl(path) { return `${API}${path}`; }
async function fetchJson(path, options = {}, timeoutMs = 15000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(apiUrl(path), { ...options, signal: controller.signal });
    const raw = await response.text();
    let data = {};
    try { data = raw ? JSON.parse(raw) : {}; } catch (_) {}
    if (!response.ok) throw new Error(data.detail || `Request failed (${response.status})`);
    return data;
  } catch (error) {
    if (error.name === 'AbortError') throw new Error('The DogTalk backend took too long to respond.');
    if (error instanceof TypeError) throw new Error('Cannot connect to the DogTalk backend.');
    throw error;
  } finally { clearTimeout(timer); }
}
function speakHuman(text) {
  if (!('speechSynthesis' in window)) return;
  speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.rate = 0.95;
  utterance.pitch = 1;
  speechSynthesis.speak(utterance);
}

// Play a real dog recording. The sentence controls the number of bark repetitions,
// but the sound itself is never synthesized or generated by an oscillator.
function playRealDogBark(text, cue) {
  const count = Math.min(Math.max((text || '').trim().split(/\s+/).filter(Boolean).length, 1), 5);
  const gap = cue === 'STOP' || cue === 'NO' ? 420 : cue === 'COME' ? 300 : 360;
  const playOne = index => {
    const audio = new Audio(REAL_DOG_BARK_URL);
    audio.preload = 'auto';
    audio.volume = cue === 'STOP' || cue === 'NO' ? 0.8 : 0.65;
    audio.playbackRate = cue === 'COME' ? 1.08 : cue === 'STOP' || cue === 'NO' ? 0.94 : 1;
    audio.addEventListener('ended', () => {
      if (index + 1 < count) setTimeout(() => playOne(index + 1), gap);
    }, { once: true });
    audio.play().catch(() => {
      $('humanResult')?.insertAdjacentHTML('beforeend', '<p class="audio-help"><i class="bi bi-info-circle-fill"></i> Tap Play Dog Vocalization again if the browser blocked the audio.</p>');
    });
  };
  playOne(0);
}

async function getMicrophone() {
  if (!navigator.mediaDevices?.getUserMedia) throw new Error('Your browser does not support microphone recording. Use Chrome or Edge over localhost.');
  return navigator.mediaDevices.getUserMedia({ audio: true });
}

async function analyzeDogAudioLocally(blob) {
  const Ctx = window.AudioContext || window.webkitAudioContext;
  if (!Ctx) throw new Error('Local audio analysis is not supported by this browser.');
  const ctx = new Ctx();
  try {
    const buffer = await ctx.decodeAudioData(await blob.arrayBuffer());
    const data = buffer.getChannelData(0), sr = buffer.sampleRate, duration = buffer.duration;
    if (!data.length) throw new Error('The recording is empty.');
    let sum = 0, crossings = 0, previous = data[0];
    const frame = Math.max(256, Math.floor(sr * 0.03)), energies = [];
    for (let i = 0; i < data.length; i++) {
      const sample = data[i]; sum += sample * sample;
      if ((sample >= 0 && previous < 0) || (sample < 0 && previous >= 0)) crossings++;
      previous = sample;
      if (i % frame === 0) {
        let total = 0; const end = Math.min(i + frame, data.length);
        for (let j = i; j < end; j++) total += data[j] * data[j];
        energies.push(Math.sqrt(total / Math.max(1, end - i)));
      }
    }
    const rms = Math.sqrt(sum / data.length), energyDb = 20 * Math.log10(Math.max(rms, 1e-8));
    const pitch = Math.max(70, Math.min(1200, (crossings / 2) / Math.max(duration, 0.01)));
    const sorted = [...energies].sort((a, b) => a - b);
    const threshold = Math.max(sorted[Math.max(0, Math.ceil(sorted.length * 0.7) - 1)] || 0.001, 0.001);
    let bursts = 0, active = false;
    energies.forEach(e => { const on = e > threshold; if (on && !active) bursts++; active = on; });
    let label = 'Uncertain / needs more context', explanation = 'The acoustic features do not strongly match the prototype categories.', confidence = 0.40;
    if (pitch >= 500 && bursts >= 3 && energyDb > -25) { label = 'Excited / playful'; explanation = 'The sound has relatively high pitch, energy and repeated bursts.'; confidence = 0.68; }
    else if (pitch >= 400 && energyDb < -30) { label = 'Attention seeking / whiny'; explanation = 'The sound is relatively high-pitched but low in energy.'; confidence = 0.62; }
    else if (energyDb > -18 && pitch < 350) { label = 'Alert / intense'; explanation = 'The recording has strong energy and a comparatively lower pitch.'; confidence = 0.64; }
    return { label, explanation, confidence, features: { duration_seconds: +duration.toFixed(2), sample_rate: sr, estimated_pitch_hz: +pitch.toFixed(1), energy_db: +energyDb.toFixed(2), sound_bursts: bursts } };
  } finally { await ctx.close(); }
}

$('dogRecordBtn').addEventListener('click', async () => {
  try {
    const stream = await getMicrophone(); dogChunks = []; dogRecorder = new MediaRecorder(stream);
    dogRecorder.ondataavailable = e => { if (e.data.size) dogChunks.push(e.data); };
    dogRecorder.onstop = async () => {
      stream.getTracks().forEach(t => t.stop());
      const blob = new Blob(dogChunks, { type: dogRecorder.mimeType || 'audio/webm' });
      $('dogPreview').src = URL.createObjectURL(blob); $('dogPreview').classList.remove('hidden');
      setRecordingUI('dogWave', 'dogStatus', false, 'Analyzing dog sound...');
      $('dogResult').classList.remove('hidden'); $('dogResult').innerHTML = '<p><i class="bi bi-cpu-fill"></i> Listening to the dog sound...</p>';
      try {
        const form = new FormData(); form.append('file', blob, 'dog-recording.webm');
        let data; try { data = await fetchJson('/api/dog-to-human', { method: 'POST', body: form }); } catch (_) { data = await analyzeDogAudioLocally(blob); }
        const message = `Your dog may be ${data.label.toLowerCase()}. ${data.explanation}`;
        $('dogResult').innerHTML = `<h3><i class="bi bi-chat-square-text-fill"></i> Human interpretation</h3><p>${message}</p><p><strong>Confidence:</strong> ${Math.round(data.confidence * 100)}%</p><div class="stats"><div class="stat">Pitch: ${data.features.estimated_pitch_hz} Hz</div><div class="stat">Energy: ${data.features.energy_db} dB</div><div class="stat">Duration: ${data.features.duration_seconds}s</div><div class="stat">Bursts: ${data.features.sound_bursts}</div></div>`;
        speakHuman(message); setRecordingUI('dogWave', 'dogStatus', false, 'Done — interpretation spoken aloud');
      } catch (error) { $('dogResult').innerHTML = `<p><i class="bi bi-x-circle-fill"></i> ${error.message}</p>`; setRecordingUI('dogWave', 'dogStatus', false, 'Analysis failed'); }
    };
    dogRecorder.start(); $('dogRecordBtn').disabled = true; $('dogStopBtn').disabled = false; setRecordingUI('dogWave', 'dogStatus', true, 'Listening to dog... bark now');
  } catch (error) { $('dogResult').classList.remove('hidden'); $('dogResult').innerHTML = `<p><i class="bi bi-x-circle-fill"></i> ${error.message}</p>`; }
});
$('dogStopBtn').addEventListener('click', () => { if (dogRecorder && dogRecorder.state !== 'inactive') dogRecorder.stop(); $('dogRecordBtn').disabled = false; $('dogStopBtn').disabled = true; });

function setupSpeechRecognition() {
  const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
  if (!SpeechRecognition) return null;
  const r = new SpeechRecognition(); r.continuous = true; r.interimResults = true; r.lang = 'en-IN';
  r.onresult = event => { let text = ''; for (let i = event.resultIndex; i < event.results.length; i++) text += event.results[i][0].transcript; transcript = text.trim(); $('transcript').textContent = transcript || 'Listening...'; };
  r.onerror = () => {}; return r;
}
function localHumanToDog(text) {
  const t = text.toLowerCase();
  const cues = [['sit','SIT','Use one consistent word and reward immediately.'],['stay','STAY','Keep the cue short and reinforce calm behavior.'],['come','COME','Use a happy voice and reward when the dog reaches you.'],['stop','STOP','Avoid shouting; use the same cue consistently.'],['down','DOWN','Pair the cue with a hand signal during training.'],['no','NO','Redirect to an acceptable behavior instead of repeating the cue.']];
  const match = cues.find(([key]) => t.includes(key));
  return match ? { cue: match[1], tip: match[2] } : { cue: 'CUSTOM', tip: 'Use a short, consistent cue and reward the behavior you want.' };
}
$('humanRecordBtn').addEventListener('click', async () => {
  try {
    const stream = await getMicrophone(); transcript = ''; $('transcript').textContent = 'Listening to your voice...'; humanRecorder = new MediaRecorder(stream);
    humanRecorder.ondataavailable = () => {};
    humanRecorder.onstop = async () => {
      stream.getTracks().forEach(t => t.stop()); if (recognition) { try { recognition.stop(); } catch (_) {} }
      $('humanResult').classList.remove('hidden'); const text = transcript.trim();
      if (!text) { $('humanResult').innerHTML = '<p><i class="bi bi-x-circle-fill"></i> No speech was detected. Allow microphone access and speak clearly.</p>'; setRecordingUI('humanWave','humanStatus',false,'No speech detected'); return; }
      $('humanResult').innerHTML = '<p><i class="bi bi-cpu-fill"></i> Converting the complete sentence...</p>';
      try {
        let data; try { data = await fetchJson('/api/human-to-dog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})}); } catch (_) { data = localHumanToDog(text); }
        $('humanResult').innerHTML = `<h3><i class="bi bi-soundwave"></i> Dog vocalization generated</h3><p><strong>Human said:</strong> ${text}</p><p><strong>Interpreted intent:</strong> ${data.cue}</p><p><strong>Pattern:</strong> ${Math.min(Math.max(text.split(/\s+/).filter(Boolean).length,2),18)} bark units based on the spoken sentence</p><p>${data.tip}</p><button id="playCueBtn" type="button"><i class="bi bi-volume-up-fill"></i> Play Dog Vocalization</button><p><small>This plays a real recorded dog bark, not a synthesized machine tone. It is an illustrative bark cue, not a proven translation into dog language.</small></p>`;
        $('playCueBtn').addEventListener('click', () => playRealDogBark(text, data.cue)); setRecordingUI('humanWave','humanStatus',false,'Done — real dog bark ready');
      } catch (error) { $('humanResult').innerHTML = `<p><i class="bi bi-x-circle-fill"></i> ${error.message}</p>`; setRecordingUI('humanWave','humanStatus',false,'Conversion failed'); }
    };
    humanRecorder.start(); recognition = setupSpeechRecognition(); if (recognition) { try { recognition.start(); } catch (_) {} }
    $('humanRecordBtn').disabled = true; $('humanStopBtn').disabled = false; setRecordingUI('humanWave','humanStatus',true,'Listening to you... speak the full sentence');
  } catch (error) { $('humanResult').classList.remove('hidden'); $('humanResult').innerHTML = `<p><i class="bi bi-x-circle-fill"></i> ${error.message}</p>`; }
});
$('humanStopBtn').addEventListener('click', () => { if (humanRecorder && humanRecorder.state !== 'inactive') humanRecorder.stop(); $('humanRecordBtn').disabled = false; $('humanStopBtn').disabled = true; });
